sudo: required
dist: trusty
language: ruby
rvm:
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - jruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
before_install:
  - gem install bundler
  - sudo apt-get -qq update
  - sudo apt-get install -y libgirepository1.0-dev gobject-introspection gir1.2-gtop-2.0
  - sudo apt-get install -y gir1.2-gtk-3.0 gir1.2-pango-1.0 gir1.2-secret-1
  - sudo apt-get install -y gir1.2-gstreamer-1.0
install:
  - bundle install --retry=3
branches:
  only:
    - master
