sudo: required
dist: trusty
language: ruby
rvm:
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - ruby-head
  - ruby-head-clang
  - jruby-9.0
  - jruby-head
  - rbx-3.7
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: ruby-head-clang
install:
  - bundle install --retry=3
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgirepository1.0-dev gobject-introspection gir1.2-gtop-2.0
  - sudo apt-get install -y gir1.2-gstreamer-1.0
  - gem install bundler
